# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Destination.destroy_all

u1 = User.create(name: "Brian")
u2 = User.create(name: "Jared")
u2 = User.create(name: "Dutch")

d1 = Destination.create(name: "New York City", description: "NYC is the most populated city in the America, with more than 8 million people currently living in NYC. It is also the most diverse U.S. city, with residents hailing from every corner of the globe. New York is a city of many names, including The Big Apple, The City That Never Sleeps, and even Gotham City.", region: "North America", country: "USA", category: "Mega City")
d2 = Destination.create(name: "Los Angeles", description: "Welcome to California’s liveliest city, entertainment capital of America, with megastar wattage and nonstop activities. Play at Universal Studios Hollywood theme park, explore world-class museums, or dance the night away in a starlet-filled club.", region: "North America", country: "USA", category: "Mega City")
d3 = Destination.create(name: "Washington D.C.", description: "Monuments and memorials, eclectic neighborhoods, true local flavor – Washington, DC is a place unlike any other. It’s your home away from home with free museums and America’s front yard.", region: "North America", country: "USA", category: "Middle Of Nowhere")
d4 = Destination.create(name: "Toronto", description: "Welcoming over 27.5 million visitors annually, Toronto is the leading tourism destination in Canada. This bold, dynamic city offers superb attractions, music and events backed by the best convention and sports facilities in Canada.", region: "North America", country: "Canada", category: "Mega City")
d5 = Destination.create(name: "Montreal", description: "Montréal is a vibrant, charismatic and welcoming city. A striking union of European charm and North American attitude, Montréal seduces visitors with a harmonious pairing of the historic and the new, from exquisite architecture to fine dining.", region: "North America", country: "Canada", category: "Middle Of Nowhere")
d6 = Destination.create(name: "Vancouver", description: "Surrounded by snow-capped mountains and deep blue sea, Vancouver is gorgeous; when the sun is shining, it's truly a sight to behold. Because of its proximity to both mountains and ocean, Vancouver is famous for offering every kind of outdoor sport and adventure.", region: "North America", country: "Canada", category: "Mega City")
d7 = Destination.create(name: "Mexico City", description: "Rising from the ruins of the Aztec capital, Tenochtitlan, Mexico City offers a unique collision of contemporary city life and historic preservation. World-class museums, restaurants and parks rub shoulders with the remains of several cultures. The nightlife, the shopping and the history make it a must-see regardless of your travel style.", region: "North America", country: "Mexico", category: "Middle Of Nowhere")
d8 = Destination.create(name: "Cancun", description: "Spend your time lounging by the beach, exploring ancient ruins, taking advantage of resort spa facilities or exploring wildlife both above and below the water, all while surrounded by Mexican culture and hospitality.", region: "North America", country: "Mexico", category: "Mega City")
d9 = Destination.create(name: "Acapulco", description: "Here you'll be busy dancing from midnight until the sun comes up. Countless nightclubs keep the evenings hopping, while Acapulco Bay and its beaches give the beautiful people a place to perfect their tans by day. Gourmet restaurants and exceptional water sports make your stay unforgettable.", region: "North America", country: "Mexico", category: "Middle Of Nowhere")

d10 = Destination.create(name: "Rio de Janeiro", description: "This diverse city is home to the world's largest urban forest, world-famous beaches, and a Carnival celebration that puts Mardi Gras to shame.", region: "South America", country: "Brazil", category: "Mega City")
d11 = Destination.create(name: "Sao Paulo", description: "Busy, cosmopolitan Sao Paulo has everything - and anything - that you're looking for. There are cutting-edge museums, art galleries, arts venues for culture addicts, and a foodie scene renowned the world over.", region: "South America", country: "Brazil", category: "Mega City")
d12 = Destination.create(name: "Brasilia", description: "Prosperous and artistic, Brasilia is today designated as a UNESCO World Heritage Site thanks to its modern architectural style and progressive urban planning. The city's futuristic vibe and perfect order appeals to travelers, as does the color and culture to be found in every part of town.", region: "South America", country: "Brazil", category: "Middle Of Nowhere")
d13 = Destination.create(name: "Cusco", description: "located high in the Andes Mountains. It was once the capital of the Incan empire, thought to have been designed in the shape of a puma, and the impressive archaeological sites like Machu Picchu are the city's major attraction.", region: "South America", country: "Peru", category: "Mega City")
d14 = Destination.create(name: "Lima", description: "It's home to more than a quarter of Peru's roughly 30 million people, has wonderful food, the beautiful Miraflores district (where you can drink while overlooking beaches lined with small rocks that form eye-catching patterns each time the tide rolls out) and excellent museums.", region: "South America", country: "Peru", category: "Middle Of Nowhere")
d15 = Destination.create(name: "Nazca", description: "Nazca is the name of a system of valleys on the southern coast of Peru. It is also the name applied to the Nazca culture that flourished in the area between 300 BC and AD 800. They were responsible for the Nazca Lines and the ceremonial city of Cahuachi.", region: "South America", country: "Peru", category: "Mega City")
d16 = Destination.create(name: "Buenos Aires", description: "Big, sprawling Buenos Aires, the capital of Argentina, is called the Paris of the South. It's cosmopolitan and yet retains a neighborhood feel in the barrios. Sightseeing and nightlife—including the sensual tango dance—is a must in this sophisticated city.", region: "South America", country: "Argentina", category: "Middle Of Nowhere")
d17 = Destination.create(name: "Bariloche", description: "San Carlos de Bariloche, commonly known as Bariloche, is a prime, all-season destination in Argentina's Patagonia. Summer sailing on Lake Nahuel Huapi on the Argentina-Chile border and skiing around European-style mountain chalets make Bariloche a favorite vacation spot.", region: "South America", country: "Argentina", category: "Mega City")
d18 = Destination.create(name: "Cordoba", description: "Called the Heartland of Argentina, Cordoba retains its colonial history and blends it with a modern tourism industry and a hefty assortment of recreational activities. Cordoba is home to many of Argentina's monuments, some of which date back to the time of Spanish colonialism. ", region: "South America", country: "Argentina", category: "Middle Of Nowhere")

d19 = Destination.create(name: "London", description: "You can't fail to be excited by London's amazing attractions. See London from above on the London Eye; meet a celebrity at Madame Tussauds; examine some of the world's most precious treasures at the British Museum or come face-to-face with the dinosaurs at the Natural History Museum.", region: "Europe", country: "England", category: "Mega City")
d20 = Destination.create(name: "Bath", description: "Soak in the same hot springs that the Romans enjoyed 2000 years ago, while reading a Jane Austen novel set in this historic town. When your skin starts to prune, take a quick side trip to marvel at Stonehenge.", region: "Europe", country: "England", category: "Mega City")
d21 = Destination.create(name: "Oxford", description: "The oldest university in the English-speaking world is only a quick day trip away from London. Pack your tweed jacket to explore the school's extensive grounds, beautiful gardens, and Harry-Potter-famous architecture.", region: "Europe", country: "England", category: "Middle Of Nowhere")
d22 = Destination.create(name: "Paris", description: "Paris is the capital of fashion, art, and instantly recognizable landmarks. There is nothing quite like seeing the city lit up at night viewed from the Eiffel Tower. Known throughout the world as the City of Light, Paris is renowned for its architecture, bridges, cathedrals and parks.", region: "Europe", country: "France", category: "Mega City")
d23 = Destination.create(name: "Bordeaux", description: "Bordeaux is synonymous with wine, and for good reason: It's France's largest fine wine producing region and it's home to a full-fledged wine museum. When you need to dry out, head to a local wine spa or spend time wandering the historic city center.", region: "Europe", country: "France", category: "Middle Of Nowhere")
d24 = Destination.create(name: "Lyon", description: "Lyon is the undisputed gastronomical capital of France and some say of the world. Travel to France's second largest metropolitan area for Saône and Rhône River views, ancient Roman ruins, and satisfied tastebuds and tummies.", region: "Europe", country: "France", category: "Mega City")
d25 = Destination.create(name: "Rome", description: "Known as the 'Eternal City', Rome was once the stronghold of the mighty Roman Empire. Built on seven hills and the banks of the River Tiber, the city is a fabulous blend of elegantly crumbling ruins, magnificent palaces and bustling piazzas, ancient cobbled alleyways and glorious open spaces.", region: "Europe", country: "Italy", category: "Middle Of Nowhere")
d26 = Destination.create(name: "Florence", description: "Florence is one of the few places where you can feel the presence of greatness, from the artworks of the Uffizi to the soaring sight of the Duomo, and it's an utterly spellbinding place to spend time.", region: "Europe", country: "Italy", category: "Mega City")
d27 = Destination.create(name: "Venice", description: "Venice is a city for lovers, with its intimate gondolas and sublime artworks. But it's more than that. It's a city for everyone. If you have an interest in art, cinema, music, or architecture, or just want to be swept away by a magical destination, Venice is a city you will adore.", region: "Europe", country: "Italy", category: "Middle Of Nowhere")

d28 = Destination.create(name: "Cairo", description: "Cairo truly is a charming place with world-class sights to see. The city sits on the ethereal River Nile and is the location of the medieval Islamic city and Coptic architecture in the old city. The world-famous Egyptian Museum boasts an incredible collection of ancient Egyptian artifacts.", region: "Africa", country: "Egypt", category: "Mega City")
d29 = Destination.create(name: "Giza", description: "Giza’s iconic Great Pyramids, which were the tallest structures in the world before the arrival of skyscrapers, sit on the desert plateau against a backdrop of the ever-encroaching hazy city skyline. The pyramids are one of the world’s most iconic ancient wonders, representing Egypt and its links to historic civilization.", region: "Africa", country: "Egypt", category: "Mega City")
d30 = Destination.create(name: "Alexandria", description: "One of the great centers of learning in the ancient world and famous for its beautiful harbor, Alexandria has seduced poets, novelists, and travelers for centuries. With its unique blend of European and Middle Eastern culture, there's nowhere quite like Alexandria.", region: "Africa", country: "Egypt", category: "Middle Of Nowhere")
d31 = Destination.create(name: "Zanzibar", description: "Zanzibar is an escape from the everyday and the ordinary, with world-class beaches, and a rich history, culture, and geography like no other in the world. It's a true tropical paradise, but with so much more to offer than just surface beauty.", region: "Africa", country: "Tanzania", category: "Mega City")
d32 = Destination.create(name: "Cape Town", description: "From the sparkling waters of the ocean to the top of Table Mountain, Cape Town will sweep you away with its beauty. In the rejuvenated facades and busy city streets, you'll find a vibrant, multicultural society with much to explore.", region: "Africa", country: "South Africa", category: "Middle Of Nowhere")
d33 = Destination.create(name: "Johannesburg", description: "Johannesburg is the economic engine of South Africa, and an important financial and business center for all of the African continent. Jo'burg, as it is affectionately called, is also a very green city; Despite its cosmopolitan urban area, Johannesburg is a great place to experience South Africa's unique and iconic wildlife.", region: "Africa", country: "South Africa", category: "Mega City")

d34 = Destination.create(name: "Beijing", description: "There are stunning historical landmarks like the Forbidden City, superb museums, and sprawling markets. Beijing has a thriving music scene, with neighborhoods like Tongzhou that are full of music clubs. And there are hidden lavender gardens such as Blues Manor, which become a blissful oasis of serenity during the summer.", region: "Asia", country: "China", category: "Mega City")
d35 = Destination.create(name: "Macao", description: "Macau is often called the 'Las Vegas of China' because of its giant casinos and glamorous nightlife, including the world's largest casino in an area devoted almost exclusively to gaming and entertainment options. Be sure to bring - or buy - your party clothes to take advantage of the exciting vibe.", region: "Asia", country: "China", category: "Mega City")
d36 = Destination.create(name: "Shanghai", description: "Shanghai is an effortless blend of ancient and modern. Join hundreds of locals as they perform their daily Tai Chi rituals in Jing'an Park or take the ferry across the Huangpu River to Pudong to see some of the tallest buildings in the world.", region: "Asia", country: "China", category: "Middle Of Nowhere")
d37 = Destination.create(name: "Tokyo", description: "Tokyo's neon lights and frantic pace may be intimidating for some, but the unique energy of the city is what makes people return. Need a break? Relax among the cherry blossoms in Ueno Park, make an appointment at an owl cafe, or sail on Lake Ashi on a pirate ship in the shadow of Mount Fuji.", region: "Asia", country: "Japan", category: "Mega City")
d38 = Destination.create(name: "Kyoto", description: "The former capital of Japan drips with history and is reputed to be the nation´s most beautiful city. With over two thousand temples and shrines, as well as numerous Zen gardens, winding cobbled alleys and traditional teahouses, Kyoto is both the spiritual and cultural capital of Japan.", region: "Asia", country: "Japan", category: "Middle Of Nowhere")
d39 = Destination.create(name: "Kanazawa", description: "With beautiful temples, ancient shrines and a range of fantastic museums, this charming city lying on the Sea of Japan is not to be missed. Wonderfully preserved, its ancient neighborhoods are lovely to wander around, with the old geisha and samurai districts being particularly delightful.", region: "Asia", country: "Japan", category: "Mega City")
d40 = Destination.create(name: "Dehli", description: "Delhi is surging mix of crumbling history, gleaming modernity and, of course, traffic. The Indian capital has long held a reputation as being jammed full of life – a place where the past and the future combine. Despite of – or perhaps because of – its cramped streets, packed markets and overflowing train stations, Delhi has a lot going for it.", region: "Asia", country: "India", category: "Middle Of Nowhere")
d41 = Destination.create(name: "Mumbai", description: "Mumbai is well known for being a city on the edge – its slums overflow with life as its skyscrapers soar to the sky. The center for India’s creative culture, fashion, food and finance, Mumbai has some of the most expensive homes in the world and some of the biggest slums in Asia.", region: "Asia", country: "India", category: "Mega City")
d42 = Destination.create(name: "Agra", description: "Agra itself sits in the shadow of its imposing monument- the Taj Mahal, but is a small and welcoming city. The ancient Mughal-era Agra Fort is an attractive spot to visit – peer over the walls here and catch your first hypnotizing glimpse of the Taj.", region: "Asia", country: "India", category: "Middle Of Nowhere")

d43 = Destination.create(name: "Sydney", description: "Modern and sophisticated, Sydney is one of the best cities to visit in Australia. With fantastic beaches and the Blue Mountains on the doorstep, you will love Sydney if you enjoy the great outdoors. A vibrant culinary scene means you won’t be short of great places to eat and drink either.", region: "Oceania", country: "Australia", category: "Mega City")
d44 = Destination.create(name: "Melbourne", description: "With its vintage shops, graffiti-covered backstreets and coffee culture, Melbourne has earned a reputation as Australia’s capital of cool. The city has plenty to see and do whether you enjoy art or sports. Located on Victoria’s famously beautiful coast, there is plenty of nature and wildlife in Melbourne as well.", region: "Oceania", country: "Australia", category: "Mega City")
d45 = Destination.create(name: "Gold Coast", description: "Famous for surfing, rollercoasters and nightclubs, the Gold Coast attracts millions of people every year. Its iconic coastline stretches for more than 60 kilometres and boasts some of Australia’s best beaches. Surrounded by tropical rainforest and mangroves, it is also an area of natural beauty.", region: "Oceania", country: "Australia", category: "Middle Of Nowhere")
d46 = Destination.create(name: "Auckland", description: "Known as the 'city of sails', Auckland is New Zealand's largest city and one of its most striking. The North Island metropolis is blessed with a spectacular waterfront, a magnificent skyline, and more beaches than many of the country's coastal resorts.", region: "Oceania", country: "New Zealand", category: "Mega City")
d47 = Destination.create(name: "Christchurch", description: "From great shopping to gorgeous rivers and stunning parks, you'll have everything you'd want access to and more. Whether you're heading out to the incredible landscape that surrounds Christchurch or simply ambling through the city center, you'll continue to see the beauty in the city and the warmth of the locals. ", region: "Oceania", country: "New Zealand", category: "Middle Of Nowhere")
d48 = Destination.create(name: "Wellington", description: "Wellington is relaxed and upbeat, full of residents who are more than willing to show you around. Embark on nature safaris and scale mountains in the same city you would shop and dance the night away.", region: "Oceania", country: "New Zealand", category: "Mega City")

